version: '3'

tasks:
  hello:
    cmds:
      - echo "Stop talking, start building."
  check_disk:
    cmds:
      - ./C:\Projects\Rayyan\Side Projects\DevOps_Projects\DevOps Cloud Challenges\Knowledge_Base\bash_scripts\is_Disk_Filling_up.sh