version: '3.8'


services:
  web:
    stdin_open: true
    tty: true
    build: .
    depends_on:
      redis:
        condition: service_healthy   
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data     
    networks:
      - appnet

volumes:
  redis_data:               
networks:
  appnet:
    driver: bridge            